# Generated by Django 3.1.1 on 2020-09-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
            ],
            options={
                'db_table': 'HomeAbout',
            },
        ),
        migrations.CreateModel(
            name='AboutSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
            ],
            options={
                'db_table': 'AboutSite',
            },
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/awerd/')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Awerd',
            },
        ),
        migrations.CreateModel(
            name='contectUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('number', models.IntegerField()),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'Contect Us',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_Name', models.CharField(max_length=255)),
                ('city_Name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Destination',
            },
        ),
        migrations.CreateModel(
            name='DestinationAboutCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='image/DestinationAboutCity/')),
            ],
            options={
                'db_table': 'AboutCity',
            },
        ),
        migrations.CreateModel(
            name='DestinationAboutCityAttraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('name_place', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/DestinationAboutCityAttraction/')),
            ],
            options={
                'db_table': 'CityAttraction',
            },
        ),
        migrations.CreateModel(
            name='DestinationAboutCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/country')),
            ],
            options={
                'db_table': 'AboutCountry',
            },
        ),
        migrations.CreateModel(
            name='DestinationBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/DestinationBanner/')),
            ],
            options={
                'db_table': 'DestinationBanner',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/gallary/')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Gallary',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'Guest Review',
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/HomeBanner/')),
                ('name_of_image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'HomeBanner',
            },
        ),
        migrations.CreateModel(
            name='HomeBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/HomeBlog/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'HomeBlog',
            },
        ),
        migrations.CreateModel(
            name='HotelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('star', models.IntegerField()),
                ('adress', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/hotels/')),
            ],
            options={
                'db_table': 'HotelList',
            },
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'Introduction',
            },
        ),
        migrations.CreateModel(
            name='Mice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/mice/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'Mice',
            },
        ),
        migrations.CreateModel(
            name='NewOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/newoffers/')),
                ('title', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'NewOffers',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='image/news/')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'New',
            },
        ),
        migrations.CreateModel(
            name='ServiceElementaryServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField()),
            ],
            options={
                'db_table': 'ServiceElementaryServices',
            },
        ),
        migrations.CreateModel(
            name='ServiceTourPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField()),
            ],
            options={
                'db_table': 'ServiceTourPackage',
            },
        ),
        migrations.CreateModel(
            name='TourByInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='image/TourByInterest')),
            ],
            options={
                'db_table': 'TourByInterest',
            },
        ),
        migrations.CreateModel(
            name='TourByRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='image/TourByRegion/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TourByRegion',
            },
        ),
    ]
