# Generated by Django 3.1.1 on 2020-09-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allpackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/allpackages/')),
                ('packages_name', models.CharField(max_length=255)),
                ('interest_name', models.CharField(max_length=255)),
                ('day', models.IntegerField()),
                ('night', models.IntegerField()),
                ('route', models.TextField()),
            ],
            options={
                'db_table': 'AllInterest',
            },
        ),
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('packages_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'PackageDetails',
            },
        ),
    ]
