# Generated by Django 3.1.1 on 2020-09-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0002_allpackages_packagedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetails',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
