# Generated by Django 3.1.1 on 2020-09-28 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0003_packagedetails_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PackageDetails',
            new_name='ALLPackageDetails',
        ),
    ]
