# Generated by Django 3.1.1 on 2020-09-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0004_auto_20200928_0531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutHome',
        ),
    ]
