# Generated by Django 3.1.1 on 2020-09-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0005_delete_abouthome'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allpackages',
            table='Allpackages',
        ),
    ]
