# Generated by Django 3.1.1 on 2020-09-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0006_auto_20200928_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpackages',
            name='region',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
