# Generated by Django 3.1.1 on 2020-10-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0009_enquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DestinationBanner',
        ),
    ]
