# Generated by Django 3.1.1 on 2020-11-11 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0010_delete_destinationbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allpackagedetails',
            options={'verbose_name_plural': 'All Package Details'},
        ),
        migrations.AlterModelOptions(
            name='allpackages',
            options={'verbose_name_plural': 'All packages'},
        ),
        migrations.AlterModelOptions(
            name='awards',
            options={'verbose_name_plural': 'Awards'},
        ),
        migrations.AlterModelOptions(
            name='contectus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name_plural': 'Destination'},
        ),
        migrations.AlterModelOptions(
            name='destinationaboutcity',
            options={'verbose_name_plural': 'Destination About City'},
        ),
        migrations.AlterModelOptions(
            name='destinationaboutcityattraction',
            options={'verbose_name_plural': 'Destination About City Attraction'},
        ),
        migrations.AlterModelOptions(
            name='destinationaboutcountry',
            options={'verbose_name_plural': 'Destination About Country '},
        ),
        migrations.AlterModelOptions(
            name='enquiry',
            options={'verbose_name_plural': 'Enquiry'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name_plural': 'Guest Review'},
        ),
        migrations.AlterModelOptions(
            name='homebanner',
            options={'verbose_name_plural': 'Home Banner'},
        ),
        migrations.AlterModelOptions(
            name='hotellist',
            options={'verbose_name_plural': 'Hotel List'},
        ),
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name_plural': 'Introduction'},
        ),
        migrations.AlterModelOptions(
            name='mice',
            options={'verbose_name_plural': 'TakeMyTrip - Happenings'},
        ),
        migrations.AlterModelOptions(
            name='newoffers',
            options={'verbose_name_plural': 'New Offers'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='serviceelementaryservices',
            options={'verbose_name_plural': 'Service Elementary Services'},
        ),
        migrations.AlterModelOptions(
            name='servicetourpackage',
            options={'verbose_name_plural': 'Service Tour Package'},
        ),
        migrations.AlterModelOptions(
            name='tourbyinterest',
            options={'verbose_name_plural': 'Tour By Interest'},
        ),
        migrations.AlterModelOptions(
            name='tourbyregion',
            options={'verbose_name_plural': 'Tour By Region'},
        ),
    ]
