# Generated by Django 3.1.1 on 2020-11-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0011_auto_20201111_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/Management/')),
            ],
            options={
                'verbose_name_plural': 'Management',
                'db_table': 'Management',
            },
        ),
    ]
